server:
  port:
    8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customerdb
    username: root
    password: admin123456
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace